name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Cache PlatformIO dependencies
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-pio

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    
    - name: Build Test Environment
      run: platformio test --without-uploading --without-testing --no-reset -e test -v
    
    - name: Build ESP32 Environment
      run: platformio test --without-uploading --without-testing --no-reset -e esp32dev -v
    
    - name: Build UPESY WROOM Environment
      run: platformio test --without-uploading --without-testing --no-reset -e upesy_wroom -v
    
    - name: Build Examples
      run: platformio test --without-uploading --without-testing --no-reset -e examples -v
    
    - name: Archive firmware
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: |
          .pio/build/*/firmware.elf
          .pio/build/*/firmware.bin
